api_platform:
    swagger:
        api_keys:
            bearer:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        formats:
            json: ['application/json']
