version: "3"
services:
  database:
    container_name: exrep_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exrep
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: exrep_php
    build:
      context: ./docker/php
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - USERNAME=${USERNAME}
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/exrep
    working_dir: /var/www/exrep
    user: "${USER_UID}:${USER_GID}"
    depends_on:
      - database
    command: >
      sh -c "
        if [ ! -f /var/www/exrep/.initialized ]; then
          composer install
          php bin/console lexik:jwt:generate-keypair --overwrite
          php bin/console doctrine:schema:create
          php bin/console doctrine:fixtures:load --no-interaction
          touch /var/www/exrep/.initialized
        fi
        exec php-fpm
      "
  nginx:
    container_name: exrep_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/exrep
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
